# Generated by Django 3.2.6 on 2021-08-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_post_authorid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='authorId',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
